### ISSUE TITLE
Breakpoint highlight color

### ISSUE THREAD

**Issue by chalu** [ceciljacob/code-plus-theme#2]
I installed this them last week and really totally love it. Thanks!!

I believe there's an issue with the choice of background color used to highlight a breakpoint in the dark blue theme. The current color combination makes it very difficult to read the text/code on the breakpoint line. 

See line 39 in the attached image where I tried to reproduce the issue. I think the level of legibility on line 41 can be maintained for breakpoints, even if using a different color.

Happy to try fixing this and raising a PR if you can hint me what option to change in the [theme-dark-blue-color-theme.json](https://github.com/ceciljacob/code-plus-theme/blob/master/theme/theme-dark-blue-color-theme.json)

**Comment by ceciljacob** [comment]
In some instances the highlighted breakpoint does display text with lowered legibility.

This will be located and fixed in the next version.

**Comment by ceciljacob** [comment]
**This bug has been fixed in the version that was recently released.**

The below line sets the background color for highlighted breakpoints at the stack frame position.

OLD - `"editor.stackFrameHighlightBackground": "#9bc4e2"`

NEW - `"editor.stackFrameHighlightBackground": "#9bc4e240"`

The new version has an alpha value added to the background color for better legibility.

**Comment by chalu** [comment]
Awesome. Thanks for this
